### ISSUE TITLE
How to infer on own data?

### ISSUE THREAD

**Issue by HeChengHui** [iSEE-Laboratory/VersReID#1]
@yanjk3  
Thank you for your work!
wonder it is possible to provide an inference script to test on my own video/images?

**Comment by yanjk3** [comment]
It is hard to provide such a script since I don't know how your data is organized. Besides, the checkpoint for inference will be released in two weeks as I am currently working on my thesis. If you provide the directory structure, I could give you some suggestions.

**Comment by HeChengHui** [comment]
@yanjk3 
I dont really have a directory structure. I would like to test it with my videos. So inputs would be the frames read with cv2.

**Comment by yanjk3** [comment]
I have uploaded the v-branch model checkpoint that can be directly used for inference: [Baidu Drive link](https://pan.baidu.com/s/190e1vHzYUry9LTivNiWM5Q?pwd=pami) and  [Google Drive link](https://drive.google.com/file/d/14Kb34AXy18PucHNxvwxvbsE1dUOdUDIT/view). 

The code does not support video input, but there are some suggestions that may be helpful.
- You should load the model and checkpoint first. Refer to the context [here](https://github.com/iSEE-Laboratory/VersReID/blob/main/multi_scene_joint_test.py#L50)
- You should fetch your video and sample some frames, forming a list of image frames
- If your video frames contain multiple people or the frames contain lots of backgrounds, you should then use a person detector to detect a bounding box for each person and crop the person from the image frames
- Then, you will obtain a list of person images, and you can input them into the v-branch to get the feature representation of each person image. These feature representations are used to compute the person's similarity. Refer to the context [here](https://github.com/iSEE-Laboratory/VersReID/blob/main/multi_scene_joint_test.py#L74).

**Comment by HeChengHui** [comment]
Thanks, i will give it a shot.

**Comment by HeChengHui** [comment]
@yanjk3 
must i download all the dataset to get the `total_classes` to use in `model = make_model(cfg, num_class=total_classes, camera_num=0, view_num=0)`?is it possible for you to provide the value to bypass the download?

**Comment by yanjk3** [comment]
Actually the classification head is not used during the re-id inference since we only need the feature representation for each person rather than the classification probability. Thus, you can specify ```total_classes``` to any value. Besides, the ```total_classes``` of the combined dataset is 5,038.

**Comment by HeChengHui** [comment]
@yanjk3 
The ckpt is missing classifier state?

```
device = "cuda"
cfg.defrost()
cfg.MODEL.AUX_LOSS = False if cfg.MODEL.AUX_PROMPT_NUMS == 0 else True
model = make_model(cfg, num_class=5038, camera_num=0, view_num=0)
ckpt = torch.load(cfg.TEST.WEIGHT, 'cpu')
new_ckpt = {}
for k, v in ckpt.items():
    print(f"{k=}, {v=}")
    if 'classifier' not in k:
        new_ckpt[k] = v
msg = model.load_state_dict(new_ckpt, strict=False)
print(f"{msg=}")
model.to(device)

>>>
msg=_IncompatibleKeys(missing_keys=['classifier.weight'], unexpected_keys=[])
Traceback (most recent call last):
  File "VersReID/test.py", line 55, in <module>
    model.to(device)
  File "/home/default/anaconda3/envs/hackathon/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1160, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/default/anaconda3/envs/hackathon/lib/python3.11/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/home/default/anaconda3/envs/hackathon/lib/python3.11/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/home/default/anaconda3/envs/hackathon/lib/python3.11/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/home/default/anaconda3/envs/hackathon/lib/python3.11/site-packages/torch/nn/modules/module.py", line 833, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "/home/default/anaconda3/envs/hackathon/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/default/anaconda3/envs/hackathon/lib/python3.11/site-packages/torch/cuda/__init__.py", line 298, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
```

**Comment by yanjk3** [comment]
Yes, the classifier state is not in the checkpoint, but you don't need the classifier for inference. Besides, the error you met seems to indicate that you do not have a GPU, rather than the model loading error.

**Comment by HeChengHui** [comment]
@yanjk3 
I managed to load the model and ckpt after changing `DEVICE_ID: ('1')` -> `DEVICE_ID: ('0')` in the config.

i managed to get the features for each person detected. Do i use Euclidean distance after normalization to find the shortest distance to the person i am finding?

**Comment by yanjk3** [comment]
Changing ```DEVICE_ID: ('1')``` -> ```DEVICE_ID: ('0')``` in the ___config___ is okay. Note that you better not specify it on the command line after modifying the config, as the value specified on the command line will cover the value in the config.

Yes, using the Euclidean distance after the normalized feature is okay. Once you get the feature representation for each person image, the remaining question is a "retrieval" problem. The commonly used similarity metrics including the Euclidean distance, cosine similarity, etc. You could search for more effective metrics than the mentioned two.
﻿

**Comment by HeChengHui** [comment]
@yanjk3 
Yes, i am not using this with any command line.

Is there a threshold that i could use to determine if the person detected is not the same as the person in my database?

**Comment by yanjk3** [comment]
A similarity threshold is needed if you want to determine if the two images are the same person. And the threshold is determined upon your data. Our code does not provide such an option since the re-id evaluation is a ranking task.

**Comment by HeChengHui** [comment]
@yanjk3 
Understand.
As my use case involves trying to re-id people in my videos based on my database, would it be better to use similarity search or ranking?

**Comment by yanjk3** [comment]
There are two options:
- Ranking the person similarity and choosing the person image with the top K highest similarity as the final results
- Ranking the person similarity and choosing the person image with higher similarity than your pre-defined threshold as the final results

Personally, I prefer the first one.

**Comment by HeChengHui** [comment]
@yanjk3 
I am currently using euclidean distance instead of cosine. when using cosine, the scores are mostly >0.80 for wrong people, and >0.90 for correct person. For euclidean, it is approx 0.20 for wrong people, and mostly <0.10 for correct person. It seems like the gap between wrong and correct person is rather small. Is that expected? or perhaps i have coded it wrong?
I have attached my script below.

[test.zip](https://github.com/iSEE-Laboratory/VersReID/files/14902460/test.zip)

**Comment by yanjk3** [comment]
The channel of the image you input into the ReID model seems to be BGR rather than RGB, which should be an error.
Try ```ref = cv2.cvtColor(ref, cv2.COLOR_BGR2RGB)``` and ```frame_crop = cv2.cvtColor(frame_crop, cv2.COLOR_BGR2RGB)```.
Hope it would work....

**Comment by HeChengHui** [comment]
sadly is about the same. I have attached reference pic and output video in the zip below.
[test.zip](https://github.com/iSEE-Laboratory/VersReID/files/14903307/test.zip)

**Comment by yanjk3** [comment]
Well, I have checked the code and data carefully and found that the model works well and the experimental phenomenon is as expected. 
﻿
As you can see, images of the same person have a smaller distance than those of different people, whatever metrics you used. For example, when using cosine similarity, 0.9 > 0.8, indicates that the images of the same person are more similar (higher cosine similarity means more similar). On the other hand, when using Euclidean distance, 0.1<0.2, representing that the images of the same person are closer (lower Euclidean distance means more similar). This is absolutely as expected.
﻿
Besides, although the margin of the distance is not significant, it can ensure images of the same person are sorted into the leading position in the candidate images, thus resulting in good Rank-1 accuracy and mAP. Hope your question is addressed and if you find this repository useful, plz kindly give a star : )

**Comment by HeChengHui** [comment]
I see. Thank you so much for your assistance and your work!
