### ISSUE TITLE
复现其他方法在prcc数据集上结果的问题

### ISSUE THREAD

**Issue by emlssyj** [iSEE-Laboratory/VersReID#4]
您好！感谢您的研究工作！我在尝试复现并比较transreid与您的方法在prcc数据集上的结果时遇到了一些问题，我使用transreid只能达到10%的mAP，想请问您论文中transreid在prcc数据集上的训练结果（mAP 57.9%）是如何达到的？需要修改哪些参数或者使用别的loss吗？

**Comment by yanjk3** [comment]
prcc数据集非常容易过拟合。印象中当时使用到的一些trick：
- early stop，印象中应该只需要训练60个ep之内
- 增大drop path，默认的0.2太小了，好像调到了0.3，0.4，还是0.5这样
- 好像也调了一下triplet loss的margin，但具体细节记不清楚了

希望对你有帮助

**Comment by emlssyj** [comment]
> prcc数据集非常容易过拟合。印象中当时使用到的一些trick：
> 
> * early stop，印象中应该只需要训练60个ep之内
> * 增大drop path，默认的0.2太小了，好像调到了0.3，0.4，还是0.5这样
> * 好像也调了一下triplet loss的margin，但具体细节记不清楚了
> 
> 希望对你有帮助

您的回答很有帮助！感谢！
