### ISSUE TITLE
How to run it on my own list of images?

### ISSUE THREAD

**Issue by barshag** [iSEE-Laboratory/VersReID#5]
Where is the params for the input directory?
( I was reading the issue about infering, and still not get it..)

**Comment by yanjk3** [comment]
We do not provide such a script. You should refer to the following points to Implement it yourslef.
- Load the model and parameter
- Use a for loop to traverse your list of images
- Feed each image into the model and obtain its feature representation
- Calculate the feature similarity between the query image and the gallery images
- Sort the similarity, the more similar the images are, the more likely they are to be the same person
